import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "../globals.css";
import Header from "@/Components/website/header";
import SideMenu from "@/Components/admin/sideMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full p-5 flex mx-auto">
          <ToastContainer />
<SideMenu/>

      <div className="flex-1">
        <div className="w-full ml-40">Header</div>
        {children}

      </div>
        </div>
      </body>
    </html>
  );
}
